source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :tvos, '12.0'

target 'Basic-Playback-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Basic-Playback-SwiftUI
  
    pod 'THEOplayerSDK-basic'

end